// swift-tools-version:6.0

import PackageDescription

let package = Package(
    name: "SwiftGraphviz",
    platforms: [
        .macOS(.v15),
        .iOS(.v18)
    ],
    products: [
        .library(name: "SwiftGraphviz", targets: ["SwiftGraphviz"]),
    ],
    targets: [
        // Pre-built Graphviz static library (layout engines only, no external deps).
        // Generated by: ./build_xcframework.sh
        .binaryTarget(
            name: "CGraphviz",
            path: "Graphviz.xcframework"
        ),

        // C bridge: static plugin registration (builtins.c) + unflatten algorithm.
        // Wraps Graphviz macros (ND_coord, ED_label, etc.) as C functions callable from Swift.
        .target(
            name: "GraphvizBridge",
            dependencies: ["CGraphviz"],
            path: "Sources/GraphvizBridge",
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("include"),
            ]
        ),

        // Swift API for Graphviz layout computation.
        .target(
            name: "SwiftGraphviz",
            dependencies: ["GraphvizBridge"],
            path: "Sources/SwiftGraphviz"
        ),

        .testTarget(
            name: "SwiftGraphvizTests",
            dependencies: ["SwiftGraphviz"]
        ),
    ]
)
